[project]
name = "practice"
version = "0.1.0"
description = "Python 练习册"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dashscope>=1.25.11",
    "dotenv>=0.9.9",
]

[dependency-groups]
dev = []
